### ISSUE TITLE
spek 2.0.1 fails to discover tests

### ISSUE THREAD

**Issue by tinetti** [JetBrains/spek#649]
upgrading from spek-2.0.0-rc.1 to spek-2.0.1 results in no tests being discovered

```
Gradle Test Executor 13 STANDARD_ERROR
    Mar 07, 2019 11:12:21 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    WARNING: TestEngine with ID 'spek2' failed to discover tests
    java.lang.IllegalStateException: Required value was null.
    	at org.spekframework.spek2.runtime.util.ClassUtil.extractPackageAndClassNames(ClassUtil.kt:7)
    	at org.spekframework.spek2.runtime.scope.PathBuilder$Companion.from(Path.kt:99)
    	at org.spekframework.spek2.junit.SpekTestEngine.discover(SpekTestEngine.kt:53)
    	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
    	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
```

the only diff in my code is updating the spek version as noted above.

here's my gradle dependencies declaration:
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-reactive:$kotlin_coroutines_version"
    implementation "io.ktor:ktor-server-netty:$ktor_version"
    implementation "io.ktor:ktor-client-apache:$ktor_version"
    implementation "org.apache.kafka:kafka-clients:$kafka_version"
    implementation "org.mongodb:mongodb-driver-reactivestreams:$mongo_version"
    implementation "com.fasterxml.jackson.core:jackson-databind:$jackson_version"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jackson_version"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:$jackson_version"

    runtimeOnly "com.google.guava:guava:$guava_version"
    runtimeOnly "org.apache.logging.log4j:log4j-slf4j-impl:$log4j_version"

    testImplementation "io.mockk:mockk:$mockk_version"
    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    testImplementation("org.spekframework.spek2:spek-dsl-jvm:$spek_version") {
        exclude group: 'org.jetbrains.kotlin'
    }
    testRuntimeOnly("org.spekframework.spek2:spek-runner-junit5:$spek_version") {
        exclude group: 'org.jetbrains.kotlin'
    }

    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_version"
    testRuntimeOnly "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
}
```

and versions:
```
guava_version=19.0
jackson_version=2.9.8
junit_version=5.1.1
kafka_version=1.1.1
ktor_version=1.1.1
kotlin_coroutines_version=1.1.0
kotlin_version=1.3.21
log4j_version=2.11.1
mockk_version=1.9
mongo_version=1.10.0
spek_version=2.0.1
```

**Comment by raniejade** [comment]
You may have an anonymous class somewhere that inherits from Spek, can you mark it with`@Ignore`.

**Comment by charleskorn** [comment]
I am seeing a similar issue with a nested data class inside a test - it doesn't inherit from `Spek`, but it is inside a class that does:

```kotlin
object MySpec : Spek({
    describe("my thing") {

        data class Scenario(val description: String, ...)

    }
})
```

`qualifiedName` is `null` for `Scenario`, so the check on line 7 of `ClassUtil.extractPackageAndClassNames` fails.

**Comment by raniejade** [comment]
@charleskorn fixed by #655, which is part of `2.0.2` (starting the release process tonight).

**Comment by charleskorn** [comment]
Great, I guess I should just be more patient then :)

**Comment by charleskorn** [comment]
I am still seeing this issue in https://github.com/charleskorn/kaml with Spek 2.0.2. 

Something in [`YamlTest`](https://github.com/charleskorn/kaml/blob/master/src/test/kotlin/com/charleskorn/kaml/YamlTest.kt) is triggering this issue. (The name of class in this case is `com.charleskorn.kaml.YamlTest$1$1$1$5$Container$Companion`, but `qualifiedName` is `null`.)

**Comment by raniejade** [comment]
@charleskorn can you give the stacktrace?

**Comment by charleskorn** [comment]
```
Gradle Test Executor 1 STANDARD_ERROR
    Apr 16, 2019 8:42:40 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    WARNING: TestEngine with ID 'spek2' failed to discover tests
    java.lang.IllegalStateException: Required value was null.
        at org.spekframework.spek2.runtime.util.ClassUtil.extractPackageAndClassNames(ClassUtil.kt:7)
        at org.spekframework.spek2.runtime.scope.PathBuilder$Companion.from(Path.kt:99)
        at org.spekframework.spek2.junit.SpekTestEngine.discover(SpekTestEngine.kt:55)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

Running the tests from IntelliJ gives a similar error.

**Comment by raniejade** [comment]
Thanks, @charleskorn! It's very helpful, I have an idea on how to fix this.
